apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-local-data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /run/desktop/mnt/host/d/cursoMicroservicios/kubernetesdata
